### ISSUE TITLE
Not an issue.

### ISSUE THREAD

**Issue by belarusrulez** [EthanNC/sst-hello-prisma#1]
Hello! Thanks for example

I am trying to do the same but for postgresql. It works in dev but does't in prod (if I do sst deploy)
Did you try deploy?

Thanks.

**Comment by belarusrulez** [comment]
also I tried to run sst dev after I set up .env and was not able to :(
```
SST ❍ ion 0.0.430  ready!

➜  App:        hello-prisma
   Stage:      belarusrulez
   Console:    https://console.sst.dev/local/hello-prisma/belarusrulez

~  Deploying

|  Error        TypeError: Cannot read properties of undefined (reading 'name')
|  at file:///Users/belarusrulez/Downloads/sst-hello-prisma/sst.config.ts:19:22
|  at Cluster.obj.getSSTLink (file:///Users/belarusrulez/Downloads/sst-hello-prisma/.sst/platform/src/components/link.ts:65:14)
|  at file:///Users/belarusrulez/Downloads/sst-hello-prisma/.sst/platform/src/components/link.ts:22:33
|  at processTicksAndRejections (node:internal/process/task_queues:77:11)
|  Error        TypeError: Cannot read properties of undefined (reading 'username')
|  at file:///Users/belarusrulez/Downloads/sst-hello-prisma/sst.config.ts:29:26
|  at DatabaseUser.obj.getSSTLink (file:///Users/belarusrulez/Downloads/sst-hello-prisma/.sst/platform/src/components/link.ts:65:14)
|  at file:///Users/belarusrulez/Downloads/sst-hello-prisma/.sst/platform/src/components/link.ts:22:33
|  at processTicksAndRejections (node:internal/process/task_queues:77:11)
|  Error        TypeError: Cannot read properties of undefined (reading 'name')
|  at file:///Users/belarusrulez/Downloads/sst-hello-prisma/sst.config.ts:19:22
|  at Cluster.obj.getSSTLink (file:///Users/belarusrulez/Downloads/sst-hello-prisma/.sst/platform/src/components/link.ts:65:14)
|  at file:///Users/belarusrulez/Downloads/sst-hello-prisma/.sst/platform/src/components/link.ts:49:24
|  at Array.map (<anonymous>)
|  at Object.build3 [as build] (file:///Users/belarusrulez/Downloads/sst-hello-prisma/.sst/platform/src/components/link.ts:48:8)
|  at file:///Users/belarusrulez/Downloads/sst-hello-prisma/.sst/platform/src/components/aws/function.ts:1088:60
|  at /Users/belarusrulez/Downloads/sst-hello-prisma/.sst/platform/node_modules/@pulumi/output.ts:404:31
|  at Generator.next (<anonymous>)
|  at /Users/belarusrulez/Downloads/sst-hello-prisma/.sst/platform/node_modules/@pulumi/pulumi/output.js:21:71
|  at new Promise (<anonymous>) {
|  promise: Promise { <rejected> [Circular *1] }
|  }

×  Failed
   TypeError: Cannot read properties of undefined (reading 'name')
       at file:///Users/belarusrulez/Downloads/sst-hello-prisma/sst.config.ts:19:22
       at Cluster.obj.getSSTLink (file:///Users/belarusrulez/Downloads/sst-hello-prisma/.sst/platform/src/components/link.ts:65:14)
       at file:///Users/belarusrulez/Downloads/sst-hello-prisma/.sst/platform/src/components/link.ts:22:33
       at processTicksAndRejections (node:internal/process/task_queues:77:11)
   TypeError: Cannot read properties of undefined (reading 'username')
       at file:///Users/belarusrulez/Downloads/sst-hello-prisma/sst.config.ts:29:26
       at DatabaseUser.obj.getSSTLink (file:///Users/belarusrulez/Downloads/sst-hello-prisma/.sst/platform/src/components/link.ts:65:14)
       at file:///Users/belarusrulez/Downloads/sst-hello-prisma/.sst/platform/src/components/link.ts:22:33
       at processTicksAndRejections (node:internal/process/task_queues:77:11)
   TypeError: Cannot read properties of undefined (reading 'name')
       at file:///Users/belarusrulez/Downloads/sst-hello-prisma/sst.config.ts:19:22
       at Cluster.obj.getSSTLink (file:///Users/belarusrulez/Downloads/sst-hello-prisma/.sst/platform/src/components/link.ts:65:14)
       at file:///Users/belarusrulez/Downloads/sst-hello-prisma/.sst/platform/src/components/link.ts:49:24
       at Array.map (<anonymous>)
       at Object.build3 [as build] (file:///Users/belarusrulez/Downloads/sst-hello-prisma/.sst/platform/src/components/link.ts:48:8)
       at file:///Users/belarusrulez/Downloads/sst-hello-prisma/.sst/platform/src/components/aws/function.ts:1088:60
       at /Users/belarusrulez/Downloads/sst-hello-prisma/.sst/platform/node_modules/@pulumi/output.ts:404:31
       at Generator.next (<anonymous>)
       at /Users/belarusrulez/Downloads/sst-hello-prisma/.sst/platform/node_modules/@pulumi/pulumi/output.js:21:71
       at new Promise (<anonymous>) {
     promise: Promise { <rejected> [Circular *1] }
   }
```
